export const MEDINGEN_SOURCE = 'MEDINGEN';

export const MEDINGEN_STATUS = {
  GENERATED: 'GENERATED',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  FAILED: 'FAILED',
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
} as const;

export const MEDINGEN_ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
} as const;
