-- AlterTable
ALTER TABLE "system_settings" 
ADD COLUMN IF NOT EXISTS "default_offline_markup" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ADD COLUMN IF NOT EXISTS "default_online_markup" DOUBLE PRECISION NOT NULL DEFAULT 85.0,
ADD COLUMN IF NOT EXISTS "default_gst" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN IF NOT EXISTS "default_retail_discount" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- AlterTable for products table pricing/markup fields
ALTER TABLE "products" 
ADD COLUMN IF NOT EXISTS "offline_markup" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ADD COLUMN IF NOT EXISTS "offline_selling_price" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "offline_auto_calculate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "online_markup" DOUBLE PRECISION NOT NULL DEFAULT 85.0,
ADD COLUMN IF NOT EXISTS "online_selling_price" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "online_auto_calculate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "wholesale_price" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "hospital_price" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "member_price" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "special_offer_price" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "retail_discount" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "round_off" BOOLEAN NOT NULL DEFAULT true;
