-- AlterTable
ALTER TABLE "system_settings" 
ADD COLUMN IF NOT EXISTS "default_offline_markup" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ADD COLUMN IF NOT EXISTS "default_online_markup" DOUBLE PRECISION NOT NULL DEFAULT 85.0,
ADD COLUMN IF NOT EXISTS "default_gst" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN IF NOT EXISTS "default_retail_discount" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
